- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCat.Client.Tests/SynchronizationContextDeadlockTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/HttpConfigFetcher.cs
implement tests to prevent synchronize context deadlocks. 
closes #17
> implement tests to prevent SynchronizationContext deadlocks (issue#17)

- appveyor.yml
Sonarcloud scans are failing due to a wrong java version, so this PR points the JAVA_HOME env variable to jdk11.
> Set java home to jdk11 for sonarcloud

- src/ConfigCat.Client.Tests/ConfigEvaluatorTestsBase.cs
- src/ConfigCat.Client.Tests/DataGovernanceTests.cs
- src/ConfigCat.Client.Tests/DeserializerTests.cs
- src/ConfigCat.Client.Tests/HttpConfigFetcherTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigDeserializer.cs
- src/ConfigCatClient/HttpConfigFetcher.cs
Users can unintentionally give bad settings to the SDK through json.NET's `JsonConvert.DefaultSettings` static property.
This PR changes the serializer handling towards a single serializer instance rather than the static `JsonConvert` methods. They always use the `DefaultSettings`, even when you override their settings parameter.
n/a
> Ensure internal serializer doesn't use the global json serializer settings

- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCat.Client.Tests/ConfigEvaluatorTestsBase.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/Configuration/ConfigurationBase.cs
- src/ConfigCatClient/Logging/LoggerWrapper.cs
- src/ConfigCatClient/Override/LocalFileDataSource.cs
In this PR I fixed a file locking issue with `FileSystemWatcher`. The watcher doesn't really care about whether the write is finished or not on a file that is changed, so our current reload function could easily fail on trying to open a locked file.
A lock-check loop was introduced to give the reload functionality more chance to open the file if it's being unlocked within 10s of trying.
I also made some consolidation around the `LogLevel`, it was kinda confusing as it was defined on both the `LoggerWrapper` and `ConsoleLogger` at the same time but it was just used on the `LoggerWrapper` really. Now the wrapper is only proxying the underlying ILogger's `LogLevel`.
> Handle files locked by another process

- CHANGELOG.md
- appveyor.yml
- src/ConfigCatClient/ConfigCatClient.csproj
Add net461 to the target frameworks list to force the usage of `System.Text.Json` rather than `Newtonsoft.Json`.
Projects using .NET 4.6.1 are falling back to the net45 version of the SDK which is fixed to `Newtonsoft.Json`.
> Add net461 target framework

- appveyor.yml
- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCat.Client.Tests/ConfigServiceTests.cs
- src/ConfigCat.Client.Tests/DataGovernanceTests.cs
- src/ConfigCat.Client.Tests/Fakes/LoggerExtensions.cs
- src/ConfigCat.Client.Tests/HttpConfigFetcherTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/ConfigService/LazyLoadConfigService.cs
- src/ConfigCatClient/ConfigService/ManualPollConfigService.cs
- src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
- src/ConfigCatClient/HttpConfigFetcher.cs
- src/ConfigCatClient/Override/FlagOverrides.cs
- src/ConfigCatClient/Override/LocalFileDataSource.cs
Previously, the SDK used both the `ILogger` from it's configuration options and an instantiated `LoggerWrapper` for logging. In this PR I'm enforcing the usage of only the `LoggerWrapper`.
> Use logger wrapper everywhere internally

- LICENSE
- src/ConfigCat.Client.Tests/ModuleInitializer.cs
- src/ConfigCat.Client.Tests/ModuleInitializerAttribute.cs
- src/ConfigCatClient/HttpConfigFetcher.cs
As it turned out, configuration of CDN servers has been changed recently to disallow deprecated security protocols older than TLS 1.2. This change broke a bunch of test cases because [.NET 4.5 does not allow TLS 1.2 by default](https://stackoverflow.com/a/58195987/8656352).
This PR proposes a solution to the problem and also adds a log message which guides the end user in the right direction when they encounter this error.
> Fixes .NET 4.5 tests

- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCat.Client.Tests/ConfigServiceTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/ConfigService/ConfigServiceLoggerExtensions.cs
- src/ConfigCatClient/ConfigService/EmptyConfigService.cs
- src/ConfigCatClient/ConfigService/IConfigService.cs
- src/ConfigCatClient/ConfigService/LazyLoadConfigService.cs
- src/ConfigCatClient/ConfigService/ManualPollConfigService.cs
- src/ConfigCatClient/ConfigService/NullConfigService.cs
- src/ConfigCatClient/Configuration/ConfigCatClientOptions.cs
- src/ConfigCatClient/IConfigCatClient.cs
- src/ConfigCatClient/PollingModes.cs
* Adds `IConfigCatClient.IsOffline` property, `IConfigCatClient.SetOnline` and `IConfigCatClient.SetOffline` methods.
* Renames `EmptyConfigService` to `NullConfigService` for better naming as this class implements the [null object design pattern](https://sourcemaking.com/design_patterns/null_object). (This is just a suggestion though, we can scrap it if you disagree.)
It's also worth mentioning that in the current implementation the client goes into offline mode implicitly when gets disposed. This also prevents the user from making forced cache refreshes (`RefreshConfig`/`RefreshConfigAsync`) on a disposed client. If you don't think that this is a good design, let's discuss it.
> Offline mode feature

- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCat.Client.Tests/ConfigServiceTests.cs
- src/ConfigCatClient/Cache/InMemoryConfigCache.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/ConfigService/LazyLoadConfigService.cs
- src/ConfigCatClient/ConfigService/ManualPollConfigService.cs
- src/ConfigCatClient/HttpConfigFetcher.cs
- src/ConfigCatClient/ProjectConfig.cs
* Improves refresh logic of `AutoPollConfigService` and `LazyLoadConfigService` to take the cache download time into account to fetch the config only if cached config is unavailable or stale.
* Also does some cleanup around `*ConfigService` classes.
Breaking changes:
* Changes `ProjectConfig` to reference type with value equality (record)
* Slightly changes the behavior of `ProjectConfig.TimeStamp` (only updated when ~download succeeds~ communication with the CDN servers succeeds, regardless of the returned status code)
> LazyLoad and AutoPoll refresh logic improvements

- src/ConfigCat.Client.Tests/ConfigCatClientCacheTests.cs
- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigCatClientCache.cs
Consider the following pattern:
```csharp
// 1. Creates a new instance of ConfigCatClient under the hood
var client1 = ConfigCatClient.Get("<KEY>");
// 2. Removes the previously created instance from the client cache
client1.Dispose();
// 3. Creates another instance of ConfigCatClient with the *same* key
var client2 = ConfigCatClient.Get("<KEY>");
// 4. Dispose can be called multiple times (it's not prohibited) but it should have no effect.
// However, if the Dispose logic just blindly removes the current cached instance by key,
// it will remove the other instance (client2), which would mess up the logic of shared instances.
// That is, we need to safeguard against this by making Dispose truly idempotent!
client1.Dispose();
```
A possible way of fixing this is presented in this PR. …
> Fixes subtle bug in the case of multiple Dispose calls

- CHANGELOG.md
- appveyor.yml
- src/ConfigCat.Client.Tests/OverrideTests.cs
- src/ConfigCatClient/Override/FlagOverrides.cs
- src/ConfigCatClient/Override/LocalDictionaryDataSource.cs
This PR contains the following:
- Introduces a new local dictionary override factory method:
```csharp
FlagOverrides LocalDictionary(IDictionary<string, object> dictionary, bool watchChanges, OverrideBehaviour overrideBehaviour)
``` 
Where the `watchChanges` parameter indicates whether the SDK should rebuild the overrides upon each read to keep track of the source dictionary's changes.
> Track the changes of the source override dictionary

- CHANGELOG.md
- src/ConfigCatClient/HttpConfigFetcher.cs
Fixes error logging in `HttpConfigFetcher.FetchInternalAsync` to include exception in the log if any (to make the behavior consistent with other SDKs.)
> Fix config fetcher-related error logging

- src/ConfigCat.Client.Tests/ConfigServiceTests.cs
- src/ConfigCat.Client.Tests/ConfigurationTests.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/Configuration/PollingMode.cs
- src/ConfigCatClient/Configuration/PollingModes.cs
Revise the ranges in which `AutoPoll.PollInterval`, `AutoPoll.MaxInitWaitTime` and `LazyLoad.CacheTimeToLive` are valid.
Also, makes infinite init wait possible in `AutoPollConfigService`.
> Fix validation of polling mode intervals

- src/ConfigCatClient/ConfigCatClient.csproj
The library referenced a specific version of the `System.Net.Http` assembly (v4.3.4), which could cause version conflict issues in the case of `net45` and `net461` targets. This PR aims to solve this by changing the reference to the built-in version (v4.0.0), which is shipped as a part of the framework.
> Prevent System.Net.Http version conflicts

- src/ConfigCatClient/ConfigCatClient.csproj
This PR is kind of a follow-up to https://github.com/configcat/.net-sdk/pull/68
I revised the package references of other targets than .NET framework targets as well and it seems to me that we have some unnecessary or questionable references:
* `System.Net.Http` (v4.3.4): this is an OOB (out-of-band) package which is for backporting newer improvements/fixes for older runtimes. However, [MS don't advise using the separate `System.Net.Http` NuGet package anymore](https://stackoverflow.com/a/58874418) because it [may lead to complications](https://github.com/dotnet/runtime/issues/20777#issuecomment-338418610) (as we also experienced that ourselves). In the case of .NET 5+, referencing the package is pointless anyway because those runtimes include a newer version. In the case of older …
> Revise dependencies

- src/ConfigCat.Client.Tests/ConfigServiceTests.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
So far the `ClientReady` event has fired in Auto Poll mode only when receiving 200, 304, 403 or 404 status code. In other cases (including the case of network errors) `maxInitWaitTime` has been waited before firing `ClientReady`.
Breaking changes:
* Change the behavior of the `ClientReady` hook to fire after the completion of the first fetch operation in Auto Poll mode - regardless of success or failure - to make the behavior consistent with other SDKs.
> Correct ClientReady hook in Auto Poll mode

- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/ConfigService/LazyLoadConfigService.cs
- src/ConfigCatClient/ConfigService/ManualPollConfigService.cs
- src/ConfigCatClient/ConfigService/NullConfigService.cs
- src/ConfigCatClient/Configuration/ConfigCatClientOptions.cs
- src/ConfigCatClient/Hooks/Hooks.cs
- src/ConfigCatClient/Hooks/SafeHooksWrapper.cs
- src/ConfigCatClient/Logging/LoggerWrapper.cs
A hook event handler which closes over the client instance should not prevent the client from being collected by the GC when user has no more references to the client.
> Fix subtle memory leak issue

- .github/workflows/linux-macOS-CI.yml
- .github/workflows/sonar-analysis.yml
- appveyor.yml
- samples/ASP.NETCore/WebApplication/Controllers/HomeController.cs
- samples/ASP.NETCore/WebApplication/WebApplication.csproj
- samples/ConsoleApp/ConsoleApp.csproj
- src/ConfigCat.Client.Tests/ConfigCat.Client.Tests.csproj
- src/ConfigCat.Client.Tests/Helpers/LoggingHelper.cs
- src/ConfigCat.Client.Tests/UserTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/Evaluation/EvaluateLogHelper.cs
- src/ConfigCatClient/Evaluation/EvaluationDetails.cs
- src/ConfigCatClient/Extensions/ObjectExtensions.cs
- src/ConfigCatClient/Extensions/SerializationExtensions.cs
- src/ConfigCatClient/Extensions/TaskExtensions.cs
- src/ConfigCatClient/FetchResult.cs
- src/ConfigCatClient/Override/IOverrideDataSource.cs
- src/ConfigCatClient/Override/LocalDictionaryDataSource.cs
- src/ConfigCatClient/Override/LocalFileDataSource.cs
- src/ConfigCatClient/ProjectConfig.cs
- src/ConfigCatClient/RefreshResult.cs
- src/ConfigCatClient/User.cs
Prepare v9.0.0 (Catnip) release
> Prepare v9.0.0 (Catnip) release

- src/ConfigCat.Client.Tests/OverrideTests.cs
- src/ConfigCatClient/Evaluation/EvaluationDetails.cs
- src/ConfigCatClient/Extensions/SerializationExtensions.cs
- src/ConfigCatClient/Logging/FormattableLogMessage.cs
- src/ConfigCatClient/Override/LocalFileDataSource.cs
- src/ConfigCatClient/User.cs
Minor improvements and fixes, see comment messages.
> Minor improvements and fixes

- src/ConfigCatClient/HttpConfigFetcher.cs
- Blazor client doesn't support AutomaticDecompression, but I think this is just a performance optimization so can do without it for now (otherwise configcat cannot be used with blazor client at all)
> Bugfix to support Dotnet Blazor WASM

- appveyor.yml
- benchmarks/NewVersionLib/BenchmarkHelper.cs
- src/ConfigCat.Client.Tests/EvaluationTestsBase.cs
- src/ConfigCat.Client.Tests/Helpers/ConfigLocation.LocalFile.cs
- src/ConfigCat.Client.Tests/SynchronizationContextDeadlockTests.cs
- src/ConfigCat.Client.Tests/UtilsTests.cs
- src/ConfigCat.Client.Tests/VariationIdTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigCatClientSnapshot.cs
- src/ConfigCatClient/Evaluation/EvaluationHelper.cs
- src/ConfigCatClient/IConfigCatClient.cs
- src/ConfigCatClient/IConfigCatClientSnapshot.cs
- src/ConfigCatClient/Logging/LogMessages.cs
Prepares v9.2.0 release.
Also, implements the missing `GetKeyAndValue` feature (since expectedly this will be the last version that supports .NET 4.5 and block waiting synchronous APIs).
> Prepare v9.2.0 release

- src/ConfigCat.Client.Tests/ConfigCat.Client.Tests.csproj
- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCat.Client.Tests/Helpers/LoggingHelper.cs
- src/ConfigCat.Client.Tests/LoggerTests.cs
- src/ConfigCat.Client.Tests/UtilsTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/Configuration/ConfigCatClientOptions.cs
- src/ConfigCatClient/Evaluation/EvaluationDetails.cs
- src/ConfigCatClient/Evaluation/EvaluationHelper.cs
- src/ConfigCatClient/FetchResult.cs
- src/ConfigCatClient/FormattableString.cs
- src/ConfigCatClient/FormattableStringFactory.cs
- src/ConfigCatClient/Hooks/Hooks.cs
- src/ConfigCatClient/Hooks/SafeHooksWrapper.cs
- src/ConfigCatClient/HttpConfigFetcher.cs
- src/ConfigCatClient/Logging/FormattableLogMessage.cs
- src/ConfigCatClient/Logging/IConfigCatLogger.cs
- src/ConfigCatClient/Logging/LogMessages.cs
- src/ConfigCatClient/Logging/LoggerExtensions.cs
- src/ConfigCatClient/Logging/LoggerWrapper.cs
- src/ConfigCatClient/RefreshResult.cs
- src/ConfigCatClient/Utils/IndentedTextBuilder.cs
- src/ConfigCatClient/Utils/LazyString.cs
Provides a new, more convenient way  (`ConfigCatClientOptions.LogFilter`) for consumers to specify custom log event filter logic.
Also, brings some performance improvements (reduced memory allocation) around log messages and evaluation log building:
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old (net6.0, LogInfo = false) |MatrixTests_ConfigV6|16.14 ms|0.149 ms|11.75 MB|
| **New** (net6.0, LogInfo = false) |	| **16.17 ms (0%)** | **0.084 ms** | **11.53 MB (-2%)** |
| Old (net48, LogInfo = false) |MatrixTests_ConfigV6|52.67 ms|0.157 ms|17.33 MB|
| **New** (net48, LogInfo = false) |	| **52.53 ms (0%)** | **0.318 ms** | **16.77 MB (-3%)** |
| Old (net6.0, LogInfo = true) |MatrixTests_ConfigV6|49.48 ms|0.204 ms|62.76 MB|
| **New** (net6.0, LogInfo = …
> Custom log filtering

- README.md
Minor UX improvements to readme:
* Brings badges closer to the top of the page.
* Moves too technical information (AOT support) further down the page.
* Make the page structure more consistent with other SDKs.
Provide links to issues relating to this pull request
> UX improvements to README.md

- README.md
- samples/UnityWebGL/README.md
Update UnityWebGL sample's README.md
> Update UnityWebGL sample's README.md

- .github/dependabot.yml
- .github/workflows/dotnet-sdk-ci.yml
- .github/workflows/keepalive.yml
- .github/workflows/linux-macOS-CI.yml
- .github/workflows/sonar-analysis.yml
- README.md
Update GitHub Actions, keep workflows alive, rearrange README.md header + increase the set of platforms covered by test runs
https://trello.com/c/7Msf9swd
https://trello.com/c/gnqqRydc
https://trello.com/c/ddiVmgU2
> Update GitHub Actions, keep workflows alive, rearrange README.md header

- samples/ASP.NETCore/WebApplication/Adapters/ConfigCatToMSLoggerAdapter.cs
- samples/ASP.NETCore/WebApplication/Program.cs
- src/ConfigCatClient/Evaluation/RolloutEvaluator.cs
- src/ConfigCatClient/Logging/FormattableLogMessage.cs
- src/ConfigCatClient/Logging/LogMessages.cs
When using `ConfigCatToMSLoggerAdapter` with Serilog, log message strings are not formatted. This is because Serilog parses the message format string under the hood and expects named parameters instead of positional ones.
This PR makes changes to the adapter so it converts positional parameters to named parameters.
Also, revises the adapter and
* corrects it to use invariant culture for formatting (as MS.Extensions.Logging and Serilog does),
* does some micro-optimization (including changing LogValues to a value type to avoid an extra heap memory allocation for each log event).
#106
n/a
n/a
> Fix ConfigCatToMSLoggerAdapter to work with Serilog

- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/ConfigService/DefaultConfigFetcher.cs
- src/ConfigCatClient/ConfigService/FetchResult.cs
- src/ConfigCatClient/ConfigService/HttpClientConfigFetcher.cs
The implementation of `HttpClientConfigFetcher` is somewhat sloppy currently because
* it doesn't correctly handle the race condition between `Dispose` and `FetchAsync`, which are not (and can't really be) synchronized,
* it allows creation of new `HttpClient` instances after `Dispose`.
This PR tightens things up in this area.
n/a
n/a
n/a
> Correct pending request vs. Dispose behavior in HttpClientConfigFetcher

- appveyor.yml
- src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
- src/ConfigCatClient/ConfigCatClient.cs
- src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
- src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
- src/ConfigCatClient/ConfigService/LazyLoadConfigService.cs
- src/ConfigCatClient/ConfigService/ManualPollConfigService.cs
- src/ConfigCatClient/ConfigService/NullConfigService.cs
- src/ConfigCatClient/Configuration/PollingMode.cs
- src/ConfigCatClient/Hooks/Hooks.cs
- src/ConfigCatClient/Hooks/NullHooks.cs
- src/ConfigCatClient/Hooks/SafeHooksWrapper.cs
- src/ConfigCatClient/Logging/LogMessages.cs
The SDK has a long-standing bug that occurs when the client instance is used in a hook event handler during client initialization. For example, a setup like
```cs
ConfigCatClient.Get("SDK-KEY", options =>
{
options.ConfigChanged += (s, e) => snapshot = ((IConfigCatClient)s!).GetValue(...);
});      
```
blows up when up-to-date config data is already available in the cache because in that case the event is raised before all fields are initialized in `ConfigCatClient` . A call like `GetValue` accesses those fields, resulting in a `NullReferenceException` exception.
This PR fixes this issue.
n/a
n/a
n/a
> Fix NRE bug when accessing client instance during client initialization
