src/ConfigCat.Client.Tests/ConfigCat.Client.Tests.csproj
src/ConfigCatClient/ConfigCatClient.csproj

Update dependencies, it contains only test related assemblies.

update dependencies (not production related)

---

src/ConfigCatClient/ConfigCatClient.csproj

updated the nuget tags in the csproj, in order to rank better in nuget search
-

updates the nuget package tags to rank better in nuget search

---

src/ConfigCat.Client.Tests/ConfigCat.Client.Tests.csproj
src/ConfigCatClient/ConfigCatClient.csproj

update dependencies (security - July)

update dependencies (security - July) 

---

CHANGELOG.md
DEPLOY.md
appveyor.yml
src/ConfigCatClient/Evaluate/RolloutEvaluator.cs

In this PR I've consolidated the percentage rule evaluation logs to match with other SDKs' logging behavior.

Consolidate perc rule logs

---

src/ConfigCatClient.sln
src/ConfigCatClient/Evaluate/EvaluateLogger.cs
src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
src/ConfigCatClient/Logging/ConsoleLogger.cs
src/ConfigCatClient/Logging/LogLevel.cs

- Rephrased the messages to help the onboarding users.
- Added color coding to the default console logger.
no tickets yet

improves logging based the latest onboarding tests

---

samples/ASP.NETCore/WebApplication/Startup.cs
src/ConfigCatClient/ConfigCatClient.csproj
src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
src/ConfigCatClient/Configuration/AutoPollConfiguration.cs
src/ConfigCatClient/Configuration/LazyLoadConfiguration.cs
src/ConfigCatClient/Configuration/PollingMode.cs
src/ConfigCatClient/Extensions/StringExtensions.cs
src/ConfigCatClient/Override/LocalFileDataSource.cs
src/ConfigCatClient/Utils/ArrayUtils.cs
src/ConfigCatClient/Versioning/SemVersion.cs

While familiarizing myself with the SDK, I found some rough edges in the implementation (at least, I think so). Each commit in this PR proposes a separate minor fix/improvement/addition described by the commit message.
A few additional notes on some of the commits:
* https://github.com/configcat/.net-sdk/commit/54c613023188e30841db9d0a5031ee251506021c: I'd even suggest using `TaskCompletionSource<T>` instead of `ManualResetEventSlim` because that's a better fit for the async/await programming model and doesn't use unmanaged resources, however [there's a gotcha around TCSs](https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/). The fix for this problem (`TaskCreationOptions.RunContinuationsAsynchronously`) is available only since .NET 4.6.1 …

Minor code quality improvements

---

CHANGELOG.md
README.md
appveyor.yml

Prepares v7.0.0 release

---

src/ConfigCat.Client.Tests/AssemblyInitializer.cs
src/ConfigCat.Client.Tests/ConfigCatClientCacheTests.cs
src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
src/ConfigCat.Client.Tests/Fakes/ExceptionThrowerHttpClientHandler.cs
src/ConfigCat.Client.Tests/Helpers/ConfigCatClientCacheExtensions.cs
src/ConfigCat.Client.Tests/HttpConfigFetcherTests.cs
src/ConfigCatClient/ConfigCatClient.cs
src/ConfigCatClient/ConfigCatClientCache.cs
src/ConfigCatClient/ConfigDeserializer.cs
src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
src/ConfigCatClient/ConfigService/ConfigServiceLoggerExtensions.cs
src/ConfigCatClient/Configuration/ConfigCatClientOptions.cs
src/ConfigCatClient/Evaluation/RolloutEvaluatorExtensions.cs
src/ConfigCatClient/Extensions/DictionaryExtensions.cs
src/ConfigCatClient/Hooks/Hooks.cs
src/ConfigCatClient/Hooks/IProvidesHooks.cs
src/ConfigCatClient/Hooks/NullHooks.cs
src/ConfigCatClient/HttpConfigFetcher.cs
src/ConfigCatClient/ProjectConfig.cs

Each commit fixes a minor issue/inconsistency with other SDKs.

Fixes minor issue(s)

---

src/ConfigCat.Client.Tests/BasicConfigCatClientIntegrationTests.cs
src/ConfigCat.Client.Tests/BasicConfigEvaluatorTests.cs
src/ConfigCat.Client.Tests/ConfigCatClientTests.cs
src/ConfigCat.Client.Tests/ConfigEvaluatorTestsBase.cs
src/ConfigCat.Client.Tests/VariationIdEvaluatorTests.cs
src/ConfigCatClient/ConfigCatClient.cs
src/ConfigCatClient/Evaluation/RolloutEvaluatorExtensions.cs
src/ConfigCatClient/IConfigCatClient.cs

* Adds `IConfigCatClient.GetAllValueDetails`/`GetAllValueDetailsAsync` methods.
* Deprecates `IConfigCatClient.GetVariationId`/`GetVariationIdAsync` and`IConfigCatClient.GetAllVariationId`/`GetAllVariationIdAsync` methods.

GetAllValueDetails feature

---

CHANGELOG.md
appveyor.yml

Prepares v7.1.0 release

---

appveyor.yml

Removes version postfix (which didn't work anyway) and tries another way to create a deterministic build.

Fix appveyor configuration

---

appveyor.yml
samples/ASP.NETCore/WebApplication/WebApplication.csproj
samples/ConsoleApp/ConsoleApp.csproj
src/ConfigCat.Client.Tests/UtilsTest.cs
src/ConfigCatClient/Logging/LogLevel.cs
src/ConfigCatClient/ProjectConfig.cs
src/ConfigCatClient/RefreshResult.cs
src/ConfigCatClient/Utils/DateTimeUtils.cs

Prepare v8.1.0 release

---

src/ConfigCat.Client.Tests/ConfigCacheTests.cs
src/ConfigCatClient/ConfigCatClient.cs

Adds tests which ensures that cache key is generated and cache payload is serialized in a platform independent way, that is, shared caching works correctly across SDKs.

Add tests for shared caching

---

src/ConfigCatClient/ConfigCatClient.cs

Removes git commit hash from the reported SDK version (which was included because of a side-effect of enabling Source Link).

Fix reported SDK version

---

src/ConfigCatClient/ConfigCatClient.cs
src/ConfigCatClient/Models/Comparator.cs
src/ConfigCatClient/Models/RolloutPercentageItem.cs

Corrects a few minor mistakes.

Fix minor mistakes

---

appveyor.yml
src/ConfigCat.Client.Tests/OverrideTests.cs
src/ConfigCatClient/Evaluation/RolloutEvaluator.cs

Prepare v8.2.0 release

---

appveyor.yml

Attempt at fixing appveyor build

Attempt at fixing appveyor build

---

appveyor.yml
src/ConfigCatClient/ConfigCatClient.csproj

October 2024 security updates

---

.github/workflows/dotnet-sdk-ci.yml
appveyor.yml
src/ConfigCatClient/Logging/IConfigCatLogger.cs

Prepare v9.4.1 release
n/a
n/a

Prepare v9.4.1 release

---

samples/UnityWebGL/Assets/Scripts/SingletonServices.cs
src/ConfigCatClient/Shims/TaskShim.cs

This PR fixes two issues related to Unity WebGL:
* Fix a regression that breaks config fetching in Unity WebGL when external cache is used.
* Fix the UnityWebGL sample script to not cause unnecessary CORS OPTIONS requests.
n/a
n/a
n/a

Fix Unity WebGL-related bugs

---

appveyor.yml

Prepare v9.4.2 release
n/a
n/a
n/a

Prepare v9.4.2 release

---

.github/workflows/dotnet-sdk-ci.yml

Move away from Appveyor - corrections 2
